server:
  port: 8066

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pusiqibao?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
mybatis:
  type-aliases-package: entity
  mapper-locations: classpath:mapper/*.xml